from typing import Protocol, Optional, List
from uuid import UUID
from domain.tenant.tenant import Tenant

class TenantRepository(Protocol):
    def get_by_id(self, tenant_id: UUID) -> Optional[Tenant]: ...
    def add(self, tenant: Tenant) -> None: ...
    def list_all(self) -> List[Tenant]: ...
