from typing import Protocol, Optional, List
from uuid import UUID
from domain.user.user import User

class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def add(self, user: User) -> None: ...
    def list_by_tenant(self, tenant_id: UUID) -> List[User]: ...
