from typing import Protocol, Optional, List
from uuid import UUID
from domain.user.user import User

class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID, conn=None) -> Optional[User]: ...
    def get_by_email(self, email: str, conn=None) -> Optional[User]: ...
    def add(self, user: User, conn=None) -> None: ...
    def list_by_tenant(self, tenant_id: UUID, conn=None) -> List[User]: ...
    def change_password(self, user_id: UUID, new_password_hash: str, conn=None) -> None: ...
